//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thoth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sedes()
        {
            this.Asignaturas = new HashSet<Asignaturas>();
            this.Cursos = new HashSet<Cursos>();
            this.Equivalencias = new HashSet<Equivalencias>();
            this.EscalaNacionales = new HashSet<EscalaNacionales>();
            this.Estudiantes = new HashSet<Estudiantes>();
            this.Grados = new HashSet<Grados>();
            this.Grupos = new HashSet<Grupos>();
            this.Jornadas = new HashSet<Jornadas>();
            this.Juicios1 = new HashSet<Juicios>();
            this.Materias = new HashSet<Materias>();
            this.Periodos = new HashSet<Periodos>();
            this.Profesores = new HashSet<Profesores>();
            this.TipoAcademicos = new HashSet<TipoAcademicos>();
            this.ValoracionLetras1 = new HashSet<ValoracionLetras>();
        }
    
        public long Id { get; set; }
        public string Codigo { get; set; }
        public string CodigoDaneNuevo { get; set; }
        public string CodigoDaneAntiguo { get; set; }
        public string CodigoConsecutivo { get; set; }
        public string Nombre { get; set; }
        public long DepartamentoId { get; set; }
        public long MunicipioId { get; set; }
        public long ZonaId { get; set; }
        public string Barrio { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Novedad { get; set; }
        public bool JornadaCompleta { get; set; }
        public bool JornadaManana { get; set; }
        public bool JornadaTarde { get; set; }
        public bool JornadaNoche { get; set; }
        public bool JornadaFinSemana { get; set; }
        public long EspecialidadId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Director { get; set; }
        public string Secretaria { get; set; }
        public bool EscalaValoracionNacional { get; set; }
        public bool RangoNumerico { get; set; }
        public int NumeroInicial { get; set; }
        public int NumeroFinal { get; set; }
        public bool ValoracionLetras { get; set; }
        public bool Juicios { get; set; }
        public bool Activo { get; set; }
        public Nullable<long> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<long> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignaturas> Asignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos> Cursos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equivalencias> Equivalencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscalaNacionales> EscalaNacionales { get; set; }
        public virtual Especialidades Especialidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grados> Grados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupos> Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jornadas> Jornadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Juicios> Juicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materias> Materias { get; set; }
        public virtual Municipios Municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Periodos> Periodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profesores> Profesores { get; set; }
        public virtual Zonas Zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoAcademicos> TipoAcademicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoracionLetras> ValoracionLetras1 { get; set; }
    }
}
