//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thoth.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThotMVCEntities : DbContext
    {
        public ThotMVCEntities()
            : base("name=ThotMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AporteParafiscales> AporteParafiscales { get; set; }
        public virtual DbSet<Ars> Ars { get; set; }
        public virtual DbSet<Asignaturas> Asignaturas { get; set; }
        public virtual DbSet<AsociacionPrivadas> AsociacionPrivadas { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Calendarios> Calendarios { get; set; }
        public virtual DbSet<CapacidadExcepcionales> CapacidadExcepcionales { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<ClasesFuncionarios> ClasesFuncionarios { get; set; }
        public virtual DbSet<Clasificaciones> Clasificaciones { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Eps> Eps { get; set; }
        public virtual DbSet<Equivalencias> Equivalencias { get; set; }
        public virtual DbSet<Escalafones> Escalafones { get; set; }
        public virtual DbSet<EscalaNacionales> EscalaNacionales { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<EstadoCiviles> EstadoCiviles { get; set; }
        public virtual DbSet<Estratos> Estratos { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Etnias> Etnias { get; set; }
        public virtual DbSet<FactorRhs> FactorRhs { get; set; }
        public virtual DbSet<FuenteRecursos> FuenteRecursos { get; set; }
        public virtual DbSet<GeneroEstudiantes> GeneroEstudiantes { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Grados> Grados { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Instituciones> Instituciones { get; set; }
        public virtual DbSet<Jornadas> Jornadas { get; set; }
        public virtual DbSet<Juicios> Juicios { get; set; }
        public virtual DbSet<LibretaMilitares> LibretaMilitares { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Metodologias> Metodologias { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<NivelEducativoDocentes> NivelEducativoDocentes { get; set; }
        public virtual DbSet<NivelEducativos> NivelEducativos { get; set; }
        public virtual DbSet<Nucleos> Nucleos { get; set; }
        public virtual DbSet<Parentescos> Parentescos { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<PoblacionVictimaConflictos> PoblacionVictimaConflictos { get; set; }
        public virtual DbSet<Prestadores> Prestadores { get; set; }
        public virtual DbSet<Profesiones> Profesiones { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }
        public virtual DbSet<PropiedadJuridicas> PropiedadJuridicas { get; set; }
        public virtual DbSet<RegimenCostos> RegimenCostos { get; set; }
        public virtual DbSet<Resguardos> Resguardos { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Sisbenes> Sisbenes { get; set; }
        public virtual DbSet<SituacionAcademicas> SituacionAcademicas { get; set; }
        public virtual DbSet<TarifaAnuales> TarifaAnuales { get; set; }
        public virtual DbSet<TipoAcademicos> TipoAcademicos { get; set; }
        public virtual DbSet<TipoCaracteres> TipoCaracteres { get; set; }
        public virtual DbSet<TipoCondiciones> TipoCondiciones { get; set; }
        public virtual DbSet<TipoDevengos> TipoDevengos { get; set; }
        public virtual DbSet<TipoDiscapacidades> TipoDiscapacidades { get; set; }
        public virtual DbSet<TipoIdentificaciones> TipoIdentificaciones { get; set; }
        public virtual DbSet<TipoNovedades> TipoNovedades { get; set; }
        public virtual DbSet<TipoRespuestas> TipoRespuestas { get; set; }
        public virtual DbSet<TipoSectorEducaciones> TipoSectorEducaciones { get; set; }
        public virtual DbSet<TipoVinculaciones> TipoVinculaciones { get; set; }
        public virtual DbSet<ValoracionLetras> ValoracionLetras { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
    }
}
